version: "3.7"

services:
  db:
    restart: always
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: administrator
      MYSQL_DATABASE: wp-ecommerce
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_TCP_PORT: 3307
      MYSQL_ROOT_HOST: localhost
    ports:
      - "3307:3307"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql