version: '3'
services:
  db:
    image: mysql:8.0
    container_name: 'mysql-db'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: administrator
      MYSQL_DATABASE: crypto-card
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123!
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_network
    depends_on:
      - db

networks:
  rabbitmq_network:
    driver: bridge